### ISSUE TITLE
ad_creator plugin classes can be described by text

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/apstools#1039]
To enable device construction from a text file, such as [`guarneri`](https://github.com/spc-group/guarneri/pull/5), it would be helpful if the plugin handling in `ad_creator()` were to recognize when the `component_class` is text.  In such cases, it should import the referenced class and make an immediate substitution.

**Comment by prjemian** [comment]
Example YAML configuration of an area detector for guarneri:

```yaml
apstools.devices.ad_creator:
  - name: adsimdet
    prefix: "ad:"
    labels: ["area_detector", "detectors"]
    plugins:
      - cam:
          class: apstools.devices.SimDetectorCam_V34
      - image
      - pva
      - hdf1:
          class: apstools.devices.AD_EpicsFileNameHDF5Plugin
          read_path_template: "/mnt/iocad/tmp/"
          write_path_template: "/tmp/"
      - roi1
      - stats1
```
