### ISSUE TITLE
Device for a bunch of motors, defined using just kwargs

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/apstools#1086]
In https://github.com/APS-4ID-POLAR/polartools/issues/89#issuecomment-2867985934, @gfabbris asks:

> Make (or already exists?) a device that just combines a bunch of motors using just kwargs.

**Comment by prjemian** [comment]
A similar concept exists in the [`hklpy2.creator`](https://blueskyproject.io/hklpy2/concepts/creator.html).

**Comment by prjemian** [comment]
Got a working prototype built.  Assembles ophyd objects based on `MotorBundle` for these YAML specifications:

```yaml
- name: s1
  motors: [x, y, z]
- name: s2
  motors: [buckle, shoe]
- name: s3
  prefix: "gp:"
  motors:
    x: m1
- name: s4
  prefix: "gp:"
  motors: [x]
- name: s5
  motors:
    theta:
        prefix: gp:m3
        labels: [dcm]
    y1:
      limits: [-50, 1]
      init_pos: -15
      labels: [arm, dcm]
    z2:
      limits: [-1, 300]
      init_pos: 75
      labels: [arm, dcm]
    ty1:
      limits: [-50, 1]
      init_pos: -15
      kind: config
      labels: [table, dcm]
    ty2:
      limits: [-1, 300]
      init_pos: 75
      kind: config
      labels: [table, dcm]
- name: s6
  prefix: "gp:"
  motors:
    u: m11
    v: m12
    w: m13
    a: null
    b: 
      class: apstools.devices.PVPositionerSoftDoneWithStop
      readback_pv: gp:float14
      setpoint_pv: gp:float4
- name: s7
  motors:
    psic:
      factory: 
        function: hklpy2.diffract.diffractometer_class_factory
        solver: hkl_soleil
        geometry: "APS POLAR"
        reals: [mu, eta, chi, phi, nu, delta]
    table:
        factory:
            function: motor_device_class_factory
            motors: [x1, x2, y1, y2, y3, z]
```
