### ISSUE TITLE
IOC container for unit testing

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/apstools#235]
Some of the code needs an EPICS IOC to serve PVs for testing.  There are now [many conda packages which provide various versions of EPICS base](https://anaconda.org/search?q=epics-base).  EPICS base includes `softIoc` which can run static databases and much testing can use this configuration without a compile of synApps.  Some packages make it very easy to run `softIoc`.

```
(base) mintadmin@mint-vm:~$ # conda create -n epics7 python=3.6 readline=6 epics-base ipython pyepics -c apsu
(epics7) mintadmin@mint-vm:~$ conda activate base
#
# need to learn the path to this conda environment
#
(epics7) mintadmin@mint-vm:~$ export LD_LIBRARY_PATH=/home/mintadmin/Apps/anaconda/envs/epics7/lib
(epics7) mintadmin@mint-vm:~$ softIoc -d /tmp/demo.db 
Starting iocInit
############################################################################
## EPICS R7.0.3
## EPICS Base built Aug  9 2019
############################################################################
iocRun: All initialization complete
epics> exit
```

There is a bash shell function to find the path to a specific conda environment.  See [`where_is_conda_env()`](https://github.com/BCDA-APS/use_bluesky/blob/master/python_installation/create_bluesky_env.sh).

**Comment by prjemian** [comment]
Is `screen` available in travis-ci?

**Comment by prjemian** [comment]
`utils.object_explorer()` needs unit testing, per #288

**Comment by prjemian** [comment]
With the shift to Github Actions in #458, it becomes easier to run one or more EPICS IOCs in [docker containers](https://stackoverflow.com/questions/57549439/how-do-i-use-docker-with-github-actions) for unit testing.  Changed the title of this issue to reflect the changed objective.

**Comment by prjemian** [comment]
An EPICS IOC is a LAN service.  Here is an explanation how to use services (provided in containers) in a workflow. https://docs.github.com/en/actions/guides/about-service-containers

Also see: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idservices

**Comment by prjemian** [comment]
See [easy example](https://github.com/prjemian/dev-ci-epics-docker/blob/79e43c699ffd78656a045c126a237d42f34e295c/.github/workflows/unit-tests-epics-base.yml):

```yml
    - name: Start IOC in Docker
      run: |
        docker ps -a
        wget https://raw.githubusercontent.com/prjemian/epics-docker/main/v1.1/n5_custom_synApps/start_xxx.sh
        bash ./start_xxx.sh gp
        docker ps -a

    - name: Install dependencies
      run: |
        $CONDA/bin/conda install epics-base --name $ENV_NAME
        $CONDA/bin/conda list -r --name $ENV_NAME
      env:
        ENV_NAME: anaconda-test-env

    - name: Run tests with caget
      run: |
        source $CONDA/bin/activate $ENV_NAME
        which caget
        caget gp:UPTIME
      env:
        ENV_NAME: anaconda-test-env
```
