### ISSUE TITLE
new format for catalogs

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/apstools#835]
With databroker 2.0 coming, there will be a new format for catalogs.

## intake: databroker 1.2.5 and previous

This is the current format.

```yml
sources:
  training:
    args:
      asset_registry_db: mongodb://localhost:27017/training-bluesky
      metadatastore_db: mongodb://localhost:27017/training-bluesky
    driver: bluesky-mongo-normalized-catalog
  class_2021_03:
    args:
      asset_registry_db: mongodb://localhost:27017/class_2021_03-bluesky
      metadatastore_db: mongodb://localhost:27017/class_2021_03-bluesky
    driver: bluesky-mongo-normalized-catalog
```

## databroker 2.0.0 uses tiled `profile.yml`

For databroker 2.0.0, it uses a `profile.yml` format.  The long term view is that databroker will
use a tiled server to provide r/w access.  But it is possible to avoid the tiled server by providing
a `direct` configuration.

```yml
training:
    direct:
        trees:
        - path: /
          tree: databroker.mongo_normalized:MongoAdapter.from_uri
          args:
            uri: mongodb://localhost:27017/training-bluesky


class_2021_03:
    direct:
        trees:
        - path: /
          tree: databroker.mongo_normalized:MongoAdapter.from_uri
          args:
            uri: mongodb://localhost:27017/class_2021_03-bluesky
```

## tiled: server `config.yml`

This is a standard tiled `config.yml` for MongoDB catalogs.

```yml
trees:
    - path: training
      tree: databroker.mongo_normalized:Tree.from_uri
      args:
            uri: mongodb://localhost:27017/training-bluesky

  - path: class_2021_03
    tree: databroker.mongo_normalized:Tree.from_uri
    args:
      # for unsecured access
      uri: mongodb://localhost:27017/class_2021_03-bluesky
```
